### ISSUE TITLE
[Feature] option to ignore/override timeout (to keep notifications until manually dismissed)

### ISSUE THREAD

**Issue by 1ace** [ErikReider/SwayNotificationCenter#257]
### Is your feature request related to a problem? Please describe.
Some apps configure a very short timeout for notifications (1sec in the case of a chat app I'm using), which means that the notifications are automatically dismissed and if I wasn't looking in the right corner of the right screen, I won't even know I received a message.

This is very obviously an app bug, but it's closed source so I can't fix the source of the problem.

### Describe the solution you'd like
A swaync option to override the timeout set by the app would be greatly appreciated :)

### Describe alternatives you've considered
I was going to suggest a boolean `ignore-timeout` kind of thing, but perhaps some people would like to override the timeout to some other value (eg. "always 10sec"), so `override-timeout` where `0` means "infinite" (and negative values mean "no override") is probably the most versatile option, and shouldn't be harder to code.

**Comment by ErikReider** [comment]
A few applications/websites that push those notifications like Android Messages dismiss the notification after a set interval unlike the expected behavior of providing a timeout and letting the notification daemon handle the visibility... The #247 issue is kinda similar.

That's why the notification isn't appearing in the Control Center. Sorry but there's nothing that I can really do about this without breaking the notification spec... This is a really irritating issue that is easily solved on the application end, but most of the time nothing will be done.

You should contact the application developer about this (as I've done in the past) and hope that they fix the issue. If you have any other questions/feedback, please let me know :)

**Comment by 1ace** [comment]
Ah right, I didn't realize that apps could also dismiss the notifications instead of using the timeout.

> Sorry but there's nothing that I can really do about this without breaking the notification spec...

Yes, both overriding/ignoring the timeout parameter and ignoring the dismiss command would definitely be against the spec, but I thought it would be ok to have an opt-in option to do that; you're the dev though, so it's your call and I respect your decision to say no ☺️

I'll try to contact the app devs 👍

**Comment by ErikReider** [comment]
I actually changed my mind on this one
