### ISSUE TITLE
[Bug] Clicking anywhere in waybar after opening notification center through it will toggle notification center

### ISSUE THREAD

**Issue by Lassebq** [ErikReider/SwayNotificationCenter#292]
**Describe the bug**
Clicking anywhere in waybar after opening notification center through custom/notification module will toggle notification center instead of whatever else you clicked, such as workspace, music player, or even background of waybar

**To Reproduce**
1. Add custom/notification example module from README
2. Click on the bell icon
3. Now click anywhere in the bar (this will close NC)
4. Clicking anywhere in the bar again (this will open NC)

**Expected behavior**
Clicking anywhere in waybar should not open notification center after you closed it

**Please provide logs if you're experiencing notification errors / bugs**
Nothing gets logged when the issue is reproduced

**Desktop**
 - OS: Arch Linux
 - Version 0.9

**Additional context**
Waybar v0.9.18-20-g9f38631c (branch 'master')

**Comment by ErikReider** [comment]
The closing of the Control Center is probably due to your waybar being below the swaync Control Center.

I'm not really sure why waybar would open the Control Center if you press anywhere on the bar, could you provide your waybar and swaync configs?

Sounds like a Waybar issue but I just wanna make sure that that's the case before potentially creating unnecessary noise in the Waybar repo

**Comment by Lassebq** [comment]
I'm pretty sure it happens with any config, it just needs to contains the example from README.
Also I fixed it by wrapping on-click like this: `sh -c 'sleep 0.1s; swaync-client -t -sw; sleep 0.1s'`

**Comment by ErikReider** [comment]
That sounds like a waybar issue. Setting the waybar layer to the same layer as swaync should fix the other issue
