### ISSUE TITLE
[Feature] Support for -r (replace) Option from notify-send

### ISSUE THREAD

**Issue by ysxninja** [ErikReider/SwayNotificationCenter#499]
Currently, `swaync` does not respect the `-r` (replace) option from `notify-send`.

#### Expected behavior:
Using `-r` with a notification ID should replace any existing notification with the same ID.

#### Current behavior:
Notifications with the same ID are not replaced, resulting in multiple notifications being shown.

Adding support for this would improve notification management.

**Comment by ErikReider** [comment]
This already works, like Discord notifications. The spec specifies that the ID should be of an existing notification, but that replacement notification should get it's own unique id

https://specifications.freedesktop.org/notification-spec/latest/basic-design.html#id-1.3.6

**Comment by Iss-in** [comment]
> This already works, like Discord notifications. The spec specifies that the ID should be of an existing notification, but that replacement notification should get it's own unique id
> 
> https://specifications.freedesktop.org/notification-spec/latest/basic-design.html#id-1.3.6

this only works for daemons process as they keep track of their last sent notification id, but for one time scripts its not possible to do this. we will need a 3rd party scripts/app to do so, but it defeats the purpose of having a notification manager

**Comment by Iss-in** [comment]
> This already works, like Discord notifications. The spec specifies that the ID should be of an existing notification, but that replacement notification should get it's own unique id
> 
> https://specifications.freedesktop.org/notification-spec/latest/basic-design.html#id-1.3.6

but this requires us to know the notification id of atleast one existing notification. hence it wont work for one time scripts. 
 
i think what needs to be implemented here that , if you run notify-send -r some_id, if no notification with such id exists, it should be alloted to this notification only, rather than giving it a random id.

ie, notify-send hello world -r 100 , will have some random notification id, not 100
now if you run it again, a new notification would be created without replacing the earlier one.
@ErikReider  @ysxninja

**Comment by bakhtiyarneyman** [comment]
It would be indeed nice if `swaync` improved on the spec i.e. relaxed the existing notification requirement. It would make my transition from dunst easier.

**Comment by Iss-in** [comment]
@ErikReider can you please reopen this

**Comment by Iss-in** [comment]
> This could break applications relying on the ID being different from before. Also, the ID isn't random, it starts from 0 and gets incremented on ever notification.


can we keep different variables for notification_count and current_notification_id 
if -r value is greater than current_notification_id, set current_notification_id to given value, and increment count 

> How does dunst handle the IDs?

it checks if there is already an notification with same id, if yes it replaces it, otherwise it assigns the id to new notification anyway

**Comment by ErikReider** [comment]
Why not just use the synchronous hint instead of mangling the spec implementation?

`notify-send "test" -h string:synchronous:some-unique-string`

**Comment by Iss-in** [comment]
wasnt aware of it at all, thanks 
seems like this will work

**Comment by ysxninja** [comment]
> Why not just use the synchronous hint instead of mangling the spec implementation?
> 
> `notify-send "test" -h string:synchronous:some-unique-string`

Keep in mind that when using string:synchronous, if the next notification is longer than the previous one, it may overlap or get cut off due to improper resizing or layout adjustments in swaync.

**Comment by ErikReider** [comment]
> > Why not just use the synchronous hint instead of mangling the spec implementation?
> > `notify-send "test" -h string:synchronous:some-unique-string`
> 
> Keep in mind that when using string:synchronous, if the next notification is longer than the previous one, it may overlap or get cut off due to improper resizing or layout adjustments in swaync.

Opened an issue, thanks for finding this :)
