### ISSUE TITLE
Change default image or default visibility

### ISSUE THREAD

**Issue by nightly-brew** [ErikReider/SwayNotificationCenter#70]
The default behaviour states that a notification always comes with a visible image, and it resorts at last to a broken_image icon when it was not possible to gather an image, app icon or desktop icon from the provided info.

The implementation works flawlessly for what I could try, but it also makes the noti history look quite strange this way, especially if one has multiple scripts sending messages to the user without icons or images.
It kinda feel broken.

Wouldn't it be better to change the default visibility to "when-available" or change the fallback image to something more generic and less broken-looking?

**Comment by ErikReider** [comment]
You've got a point. If we use notification categories (mail, social, etc) we can set a custom icon for that category. The default icon isn't really that pretty so we probably need a new one too

**Comment by nightly-brew** [comment]
Would you rather use icon-theme icons or like for the sounds, go with a custom image path?

For these one, I'm more for sticking with the theme.
In comparison to the sound theme spec, the icon one really got more love in these years.

**Comment by ErikReider** [comment]
I'd go with the icon-theme

**Comment by WhyNotHugo** [comment]
I find the default image confusing too -- when an application specified no image, just showing a generic "photo" image makes little sense. It gives an impression that the notification is somehow related to a photo application.

I think if an application specified "no icon", it's best to respect that rather than try and show a fallback -- I can't think of any icon that would add clarity to **all** notifications without icons.

**Comment by ErikReider** [comment]
"when-available" should now be the default :)

**Comment by WhyNotHugo** [comment]
Looking good, thanks!
